#spring.profiles.active=default
#spring.application.name=lusofona tfc spring boot training
#server.port=8083
##logging.level.root=DEBUG
#
### MySQL DataSource
#spring.datasource.url=jdbc:mysql://localhost:3306/tfc_cto?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false&useTimezone=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=Abboniertmich
#
### H2 DataSource
##spring.datasource.url=jdbc:h2:mem:db
##spring.datasource.url=jdbc:h2:file:./target/h2;AUTO_SERVER=TRUE
##spring.datasource.driverClassName=org.h2.Driver
##spring.datasource.username=root
##spring.datasource.password=root
##spring.h2.console.enabled=true
#
### JPA/Hibernate
#spring.jpa.show-sql=true
##spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
##spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.H2Dialect



#Version from Video
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tfc_cto?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: Abboniertmich
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
  #limits size of files 2 b sent and received, might need 2 change later on
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 3600000
      #Version from video, i think he said you don't need this one
  server:
    port: 8083
    error:
      path: /user/error
      whitelabel:
        enabled: false
